/*
 * Copyright (c) 2021 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define APACHE_HTTPD "/usr/sbin/apache2"

#define APACHE_MODULE_DIR /usr/lib/apache2/modules

#define APACHE_PHP_MODULE_FILE /usr/lib/apache2/modules/libphp7.2.so

#define APACHE_SSL_MODULE_DIR /usr/lib/apache2/modules

#define GETTEXT_PACKAGE "libsoup-2.4"

#define HAVE_APACHE

#define HAVE_GMTIME_R 1

#define IF_HAVE_MOD_UNIXD #

#define IF_HAVE_PHP 

#define IF_HAVE_PHP_XMLRPC ;

#define LOCALEDIR "/usr/local/share/locale"

#define PACKAGE_VERSION "2.71.0"

#define _SOUP_EXTERN __attribute__((visibility("default"))) extern

