/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define APACHE_HTTPD "/usr/sbin/apache2"

#define APACHE_MODULE_DIR /usr/lib/apache2/modules

#define APACHE_PHP_MODULE_FILE /usr/lib/apache2/modules/libphp7.2.so

#define APACHE_SSL_MODULE_DIR /usr/lib/apache2/modules

#define GETTEXT_PACKAGE "libsoup-2.4"

#define HAVE_APACHE

#define HAVE_GMTIME_R 1

#define IF_HAVE_MOD_UNIXD #

#define IF_HAVE_PHP 

#define IF_HAVE_PHP_XMLRPC ;

#define LOCALEDIR "/usr/local/share/locale"

#define PACKAGE_VERSION "2.71.0"

#define _SOUP_EXTERN __attribute__((visibility("default"))) extern

